target = "docs/rfcs/0001-mcp-server.md#7-error-handling-requirements"

# 7. Error Handling Requirements
#
# The server:
# - MUST return standardized error responses for all operations
# - MUST include error codes and descriptive messages
# - MUST handle JSON-RPC protocol errors
# - MUST provide stack traces in development mode only
# - MUST log all errors appropriately
# - SHOULD include error recovery suggestions where applicable
# - SHOULD maintain error consistency across all endpoints
# 
# Error responses MUST include:
# - An error code
# - A human-readable message
# - The source of the error
# - Contextual information to aid debugging

[[spec]]
level = "MUST"
quote = '''
- MUST return standardized error responses for all operations
'''

[[spec]]
level = "MUST"
quote = '''
- MUST include error codes and descriptive messages
'''

[[spec]]
level = "MUST"
quote = '''
- MUST handle JSON-RPC protocol errors
'''

[[spec]]
level = "MUST"
quote = '''
- MUST provide stack traces in development mode only
'''

[[spec]]
level = "MUST"
quote = '''
- MUST log all errors appropriately
'''

[[spec]]
level = "SHOULD"
quote = '''
- SHOULD include error recovery suggestions where applicable
'''

[[spec]]
level = "SHOULD"
quote = '''
- SHOULD maintain error consistency across all endpoints
'''

[[spec]]
level = "MUST"
quote = '''
Error responses MUST include:
'''

