[implementation]
[implementation.py]
patterns = ["src/**/*.py", "test/**/*.py"]
comment-style = { meta = "#//=", content = "#//#" }
[spec.markdown]
patterns = ["duvet-specification/duvet-specification.md"]
[report]
[report.blob]
url = "https://github.com/awslabs/duvet/blob/"
[report.issue]
url = "https://github.com/awslabs/duvet/issues"
[mode]
legacy = false