[implementation]
[implementation.py]
patterns = ["src/**/*.py", "test/**/*.py"]
comment-style = { meta = "#//=", content = "#//#" }
[spec.txt]
patterns = ["duvet-specification/compliance/duvet-specification.txt"]
[report]
[report.blob]
url = "https://github.com/awslabs/duvet/blob/"
[report.issue]
url = "https://github.com/awslabs/duvet/issues"
[mode]
legacy = false