[implementation]
[implementation.py]
patterns = ["src/**/*.py", "test/**/*.py"]
comment-style = { meta = "# //=", content = "# //#" }
[implementation.js]
patterns = ["www/src/*.js"]
comment-style = { meta = "//=", content = "//#" }
[implementation.txt]
patterns = ["compliance_exceptions/exception.txt"]
comment-style = { meta = "//=", content = "//#" }
#[spec.toml]
#path = "duvet-specification"
#patterns = ["compliance/**/*.toml"]
[spec.txt]
path = "duvet-specification"
patterns = ["compliance/duvet-specification.txt"]
#[spec.md]
#path = "duvet-specification"
#patterns = ["duvet-specification.md"]
[report]
[report.blob]
url = "https://github.com/awslabs/duvet/tree/sprint-demo/"
[report.issue]
url = "https://github.com/awslabs/duvet/issues"
[mode]
legacy = true
