[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
yanked = "deny"
ignore = [
    "RUSTSEC-2021-0139" # structopt is still using clap v2
]

[bans]
multiple-versions = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "neither"
copyleft = "deny"
confidence-threshold = 0.90
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "Unicode-DFS-2016",
    "Zlib",
]
