# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Static reference of refs json file for Duvet."""

REFS_JSON = {
    "refs": [
        {},
        {"todo": True},
        {"exception": True},
        {"exception": True, "todo": True},
        {"test": True},
        {"test": True, "todo": True},
        {"test": True, "exception": True},
        {"test": True, "exception": True, "todo": True},
        {"implication": True},
        {"implication": True, "todo": True},
        {"implication": True, "exception": True},
        {"implication": True, "exception": True, "todo": True},
        {"implication": True, "test": True},
        {"implication": True, "test": True, "todo": True},
        {"implication": True, "test": True, "exception": True},
        {"implication": True, "test": True, "exception": True, "todo": True},
        {"citation": True},
        {"citation": True, "todo": True},
        {"citation": True, "exception": True},
        {"citation": True, "exception": True, "todo": True},
        {"citation": True, "test": True},
        {"citation": True, "test": True, "todo": True},
        {"citation": True, "test": True, "exception": True},
        {"citation": True, "test": True, "exception": True, "todo": True},
        {"citation": True, "implication": True},
        {"citation": True, "implication": True, "todo": True},
        {"citation": True, "implication": True, "exception": True},
        {"citation": True, "implication": True, "exception": True, "todo": True},
        {"citation": True, "implication": True, "test": True},
        {"citation": True, "implication": True, "test": True, "todo": True},
        {"citation": True, "implication": True, "test": True, "exception": True},
        {"citation": True, "implication": True, "test": True, "exception": True, "todo": True},
        {"spec": True},
        {"spec": True, "todo": True},
        {"spec": True, "exception": True},
        {"spec": True, "exception": True, "todo": True},
        {"spec": True, "test": True},
        {"spec": True, "test": True, "todo": True},
        {"spec": True, "test": True, "exception": True},
        {"spec": True, "test": True, "exception": True, "todo": True},
        {"spec": True, "implication": True},
        {"spec": True, "implication": True, "todo": True},
        {"spec": True, "implication": True, "exception": True},
        {"spec": True, "implication": True, "exception": True, "todo": True},
        {"spec": True, "implication": True, "test": True},
        {"spec": True, "implication": True, "test": True, "todo": True},
        {"spec": True, "implication": True, "test": True, "exception": True},
        {"spec": True, "implication": True, "test": True, "exception": True, "todo": True},
        {"spec": True, "citation": True},
        {"spec": True, "citation": True, "todo": True},
        {"spec": True, "citation": True, "exception": True},
        {"spec": True, "citation": True, "exception": True, "todo": True},
        {"spec": True, "citation": True, "test": True},
        {"spec": True, "citation": True, "test": True, "todo": True},
        {"spec": True, "citation": True, "test": True, "exception": True},
        {"spec": True, "citation": True, "test": True, "exception": True, "todo": True},
        {"spec": True, "citation": True, "implication": True},
        {"spec": True, "citation": True, "implication": True, "todo": True},
        {"spec": True, "citation": True, "implication": True, "exception": True},
        {"spec": True, "citation": True, "implication": True, "exception": True, "todo": True},
        {"spec": True, "citation": True, "implication": True, "test": True},
        {"spec": True, "citation": True, "implication": True, "test": True, "todo": True},
        {"spec": True, "citation": True, "implication": True, "test": True, "exception": True},
        {"spec": True, "citation": True, "implication": True, "test": True, "exception": True, "todo": True},
        {"level": "MAY"},
        {"todo": True, "level": "MAY"},
        {"exception": True, "level": "MAY"},
        {"exception": True, "todo": True, "level": "MAY"},
        {"test": True, "level": "MAY"},
        {"test": True, "todo": True, "level": "MAY"},
        {"test": True, "exception": True, "level": "MAY"},
        {"test": True, "exception": True, "todo": True, "level": "MAY"},
        {"implication": True, "level": "MAY"},
        {"implication": True, "todo": True, "level": "MAY"},
        {"implication": True, "exception": True, "level": "MAY"},
        {"implication": True, "exception": True, "todo": True, "level": "MAY"},
        {"implication": True, "test": True, "level": "MAY"},
        {"implication": True, "test": True, "todo": True, "level": "MAY"},
        {"implication": True, "test": True, "exception": True, "level": "MAY"},
        {"implication": True, "test": True, "exception": True, "todo": True, "level": "MAY"},
        {"citation": True, "level": "MAY"},
        {"citation": True, "todo": True, "level": "MAY"},
        {"citation": True, "exception": True, "level": "MAY"},
        {"citation": True, "exception": True, "todo": True, "level": "MAY"},
        {"citation": True, "test": True, "level": "MAY"},
        {"citation": True, "test": True, "todo": True, "level": "MAY"},
        {"citation": True, "test": True, "exception": True, "level": "MAY"},
        {"citation": True, "test": True, "exception": True, "todo": True, "level": "MAY"},
        {"citation": True, "implication": True, "level": "MAY"},
        {"citation": True, "implication": True, "todo": True, "level": "MAY"},
        {"citation": True, "implication": True, "exception": True, "level": "MAY"},
        {"citation": True, "implication": True, "exception": True, "todo": True, "level": "MAY"},
        {"citation": True, "implication": True, "test": True, "level": "MAY"},
        {"citation": True, "implication": True, "test": True, "todo": True, "level": "MAY"},
        {"citation": True, "implication": True, "test": True, "exception": True, "level": "MAY"},
        {"citation": True, "implication": True, "test": True, "exception": True, "todo": True, "level": "MAY"},
        {"spec": True, "level": "MAY"},
        {"spec": True, "todo": True, "level": "MAY"},
        {"spec": True, "exception": True, "level": "MAY"},
        {"spec": True, "exception": True, "todo": True, "level": "MAY"},
        {"spec": True, "test": True, "level": "MAY"},
        {"spec": True, "test": True, "todo": True, "level": "MAY"},
        {"spec": True, "test": True, "exception": True, "level": "MAY"},
        {"spec": True, "test": True, "exception": True, "todo": True, "level": "MAY"},
        {"spec": True, "implication": True, "level": "MAY"},
        {"spec": True, "implication": True, "todo": True, "level": "MAY"},
        {"spec": True, "implication": True, "exception": True, "level": "MAY"},
        {"spec": True, "implication": True, "exception": True, "todo": True, "level": "MAY"},
        {"spec": True, "implication": True, "test": True, "level": "MAY"},
        {"spec": True, "implication": True, "test": True, "todo": True, "level": "MAY"},
        {"spec": True, "implication": True, "test": True, "exception": True, "level": "MAY"},
        {"spec": True, "implication": True, "test": True, "exception": True, "todo": True, "level": "MAY"},
        {"spec": True, "citation": True, "level": "MAY"},
        {"spec": True, "citation": True, "todo": True, "level": "MAY"},
        {"spec": True, "citation": True, "exception": True, "level": "MAY"},
        {"spec": True, "citation": True, "exception": True, "todo": True, "level": "MAY"},
        {"spec": True, "citation": True, "test": True, "level": "MAY"},
        {"spec": True, "citation": True, "test": True, "todo": True, "level": "MAY"},
        {"spec": True, "citation": True, "test": True, "exception": True, "level": "MAY"},
        {"spec": True, "citation": True, "test": True, "exception": True, "todo": True, "level": "MAY"},
        {"spec": True, "citation": True, "implication": True, "level": "MAY"},
        {"spec": True, "citation": True, "implication": True, "todo": True, "level": "MAY"},
        {"spec": True, "citation": True, "implication": True, "exception": True, "level": "MAY"},
        {"spec": True, "citation": True, "implication": True, "exception": True, "todo": True, "level": "MAY"},
        {"spec": True, "citation": True, "implication": True, "test": True, "level": "MAY"},
        {"spec": True, "citation": True, "implication": True, "test": True, "todo": True, "level": "MAY"},
        {"spec": True, "citation": True, "implication": True, "test": True, "exception": True, "level": "MAY"},
        {
            "spec": True,
            "citation": True,
            "implication": True,
            "test": True,
            "exception": True,
            "todo": True,
            "level": "MAY",
        },
        {"level": "SHOULD"},
        {"todo": True, "level": "SHOULD"},
        {"exception": True, "level": "SHOULD"},
        {"exception": True, "todo": True, "level": "SHOULD"},
        {"test": True, "level": "SHOULD"},
        {"test": True, "todo": True, "level": "SHOULD"},
        {"test": True, "exception": True, "level": "SHOULD"},
        {"test": True, "exception": True, "todo": True, "level": "SHOULD"},
        {"implication": True, "level": "SHOULD"},
        {"implication": True, "todo": True, "level": "SHOULD"},
        {"implication": True, "exception": True, "level": "SHOULD"},
        {"implication": True, "exception": True, "todo": True, "level": "SHOULD"},
        {"implication": True, "test": True, "level": "SHOULD"},
        {"implication": True, "test": True, "todo": True, "level": "SHOULD"},
        {"implication": True, "test": True, "exception": True, "level": "SHOULD"},
        {"implication": True, "test": True, "exception": True, "todo": True, "level": "SHOULD"},
        {"citation": True, "level": "SHOULD"},
        {"citation": True, "todo": True, "level": "SHOULD"},
        {"citation": True, "exception": True, "level": "SHOULD"},
        {"citation": True, "exception": True, "todo": True, "level": "SHOULD"},
        {"citation": True, "test": True, "level": "SHOULD"},
        {"citation": True, "test": True, "todo": True, "level": "SHOULD"},
        {"citation": True, "test": True, "exception": True, "level": "SHOULD"},
        {"citation": True, "test": True, "exception": True, "todo": True, "level": "SHOULD"},
        {"citation": True, "implication": True, "level": "SHOULD"},
        {"citation": True, "implication": True, "todo": True, "level": "SHOULD"},
        {"citation": True, "implication": True, "exception": True, "level": "SHOULD"},
        {"citation": True, "implication": True, "exception": True, "todo": True, "level": "SHOULD"},
        {"citation": True, "implication": True, "test": True, "level": "SHOULD"},
        {"citation": True, "implication": True, "test": True, "todo": True, "level": "SHOULD"},
        {"citation": True, "implication": True, "test": True, "exception": True, "level": "SHOULD"},
        {"citation": True, "implication": True, "test": True, "exception": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "level": "SHOULD"},
        {"spec": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "exception": True, "level": "SHOULD"},
        {"spec": True, "exception": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "test": True, "level": "SHOULD"},
        {"spec": True, "test": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "test": True, "exception": True, "level": "SHOULD"},
        {"spec": True, "test": True, "exception": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "implication": True, "level": "SHOULD"},
        {"spec": True, "implication": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "implication": True, "exception": True, "level": "SHOULD"},
        {"spec": True, "implication": True, "exception": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "implication": True, "test": True, "level": "SHOULD"},
        {"spec": True, "implication": True, "test": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "implication": True, "test": True, "exception": True, "level": "SHOULD"},
        {"spec": True, "implication": True, "test": True, "exception": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "exception": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "exception": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "test": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "test": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "test": True, "exception": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "test": True, "exception": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "implication": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "implication": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "implication": True, "exception": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "implication": True, "exception": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "implication": True, "test": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "implication": True, "test": True, "todo": True, "level": "SHOULD"},
        {"spec": True, "citation": True, "implication": True, "test": True, "exception": True, "level": "SHOULD"},
        {
            "spec": True,
            "citation": True,
            "implication": True,
            "test": True,
            "exception": True,
            "todo": True,
            "level": "SHOULD",
        },
        {"level": "MUST"},
        {"todo": True, "level": "MUST"},
        {"exception": True, "level": "MUST"},
        {"exception": True, "todo": True, "level": "MUST"},
        {"test": True, "level": "MUST"},
        {"test": True, "todo": True, "level": "MUST"},
        {"test": True, "exception": True, "level": "MUST"},
        {"test": True, "exception": True, "todo": True, "level": "MUST"},
        {"implication": True, "level": "MUST"},
        {"implication": True, "todo": True, "level": "MUST"},
        {"implication": True, "exception": True, "level": "MUST"},
        {"implication": True, "exception": True, "todo": True, "level": "MUST"},
        {"implication": True, "test": True, "level": "MUST"},
        {"implication": True, "test": True, "todo": True, "level": "MUST"},
        {"implication": True, "test": True, "exception": True, "level": "MUST"},
        {"implication": True, "test": True, "exception": True, "todo": True, "level": "MUST"},
        {"citation": True, "level": "MUST"},
        {"citation": True, "todo": True, "level": "MUST"},
        {"citation": True, "exception": True, "level": "MUST"},
        {"citation": True, "exception": True, "todo": True, "level": "MUST"},
        {"citation": True, "test": True, "level": "MUST"},
        {"citation": True, "test": True, "todo": True, "level": "MUST"},
        {"citation": True, "test": True, "exception": True, "level": "MUST"},
        {"citation": True, "test": True, "exception": True, "todo": True, "level": "MUST"},
        {"citation": True, "implication": True, "level": "MUST"},
        {"citation": True, "implication": True, "todo": True, "level": "MUST"},
        {"citation": True, "implication": True, "exception": True, "level": "MUST"},
        {"citation": True, "implication": True, "exception": True, "todo": True, "level": "MUST"},
        {"citation": True, "implication": True, "test": True, "level": "MUST"},
        {"citation": True, "implication": True, "test": True, "todo": True, "level": "MUST"},
        {"citation": True, "implication": True, "test": True, "exception": True, "level": "MUST"},
        {"citation": True, "implication": True, "test": True, "exception": True, "todo": True, "level": "MUST"},
        {"spec": True, "level": "MUST"},
        {"spec": True, "todo": True, "level": "MUST"},
        {"spec": True, "exception": True, "level": "MUST"},
        {"spec": True, "exception": True, "todo": True, "level": "MUST"},
        {"spec": True, "test": True, "level": "MUST"},
        {"spec": True, "test": True, "todo": True, "level": "MUST"},
        {"spec": True, "test": True, "exception": True, "level": "MUST"},
        {"spec": True, "test": True, "exception": True, "todo": True, "level": "MUST"},
        {"spec": True, "implication": True, "level": "MUST"},
        {"spec": True, "implication": True, "todo": True, "level": "MUST"},
        {"spec": True, "implication": True, "exception": True, "level": "MUST"},
        {"spec": True, "implication": True, "exception": True, "todo": True, "level": "MUST"},
        {"spec": True, "implication": True, "test": True, "level": "MUST"},
        {"spec": True, "implication": True, "test": True, "todo": True, "level": "MUST"},
        {"spec": True, "implication": True, "test": True, "exception": True, "level": "MUST"},
        {"spec": True, "implication": True, "test": True, "exception": True, "todo": True, "level": "MUST"},
        {"spec": True, "citation": True, "level": "MUST"},
        {"spec": True, "citation": True, "todo": True, "level": "MUST"},
        {"spec": True, "citation": True, "exception": True, "level": "MUST"},
        {"spec": True, "citation": True, "exception": True, "todo": True, "level": "MUST"},
        {"spec": True, "citation": True, "test": True, "level": "MUST"},
        {"spec": True, "citation": True, "test": True, "todo": True, "level": "MUST"},
        {"spec": True, "citation": True, "test": True, "exception": True, "level": "MUST"},
        {"spec": True, "citation": True, "test": True, "exception": True, "todo": True, "level": "MUST"},
        {"spec": True, "citation": True, "implication": True, "level": "MUST"},
        {"spec": True, "citation": True, "implication": True, "todo": True, "level": "MUST"},
        {"spec": True, "citation": True, "implication": True, "exception": True, "level": "MUST"},
        {"spec": True, "citation": True, "implication": True, "exception": True, "todo": True, "level": "MUST"},
        {"spec": True, "citation": True, "implication": True, "test": True, "level": "MUST"},
        {"spec": True, "citation": True, "implication": True, "test": True, "todo": True, "level": "MUST"},
        {"spec": True, "citation": True, "implication": True, "test": True, "exception": True, "level": "MUST"},
        {
            "spec": True,
            "citation": True,
            "implication": True,
            "test": True,
            "exception": True,
            "todo": True,
            "level": "MUST",
        },
    ]
}
