[package]
name = "duvet"
version = "0.3.0"
description = "A requirements traceability tool"
authors = ["Cameron Bytheway <bythewc@amazon.com>", "Ryan Emery <ryanemer@amazon.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/awslabs/duvet"
include = [
    "/src/**/*.rs",
    "/www/public",
]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
duvet-core = { version = "0.1", path = "../duvet-core" }
fnv = { version = "1", default-features = false }
futures = { version = "0.3" }
glob = "0.3"
lazy_static = "1"
once_cell = "1"
pathdiff = "0.2"
pulldown-cmark = { version = "0.12", default-features = false }
rayon = "1"
regex = "1"
reqwest = { version = "0.12", features = ["blocking", "native-tls"] }
serde = { version = "1", features = ["derive"] }
slug = { version = "0.1" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
toml = "0.5"
triple_accel = "0.4"
url = "2"
v_jsonescape = "0.7"

[dev-dependencies]
insta = { version = "1", features = ["json"] }
serde_json = "1"
tempfile = "3"

