target = "../duvet-specification.txt#2.2.4"

# 2.2.4.  Formats
#
# Duvet MUST be able to parse specifications formatted as:
# 
# *  markdown
# 
# *  ietf

[[spec]]
level = "MUST"
quote = '''
Duvet MUST be able to parse specifications formatted as:
'''

