target = "../duvet-specification.txt#2.5.1"

# 2.5.1.  Implemented
#
# A specification requirement MUST be labeled "Implemented" if there
# exists at least one matching annotation of type:
# 
# *  citation
# 
# *  untestable
# 
# *  implication

[[spec]]
level = "MUST"
quote = '''
A specification requirement MUST be labeled "Implemented" if there
exists at least one matching annotation of type:
'''

