target = "compliance/hello-world.txt#2.1"

# 2.1.  Print
#
# Python project MUST print hello.  This is words after it.
# 
# This is words before it.  Python Project MUST print world.

[[spec]]
level = "MUST"
quote = '''
Python project MUST print hello.
'''

[[spec]]
level = "MUST"
quote = '''
Python Project MUST print world.
'''

