target = "compliance/duvet-specification.txt#2.2.2"

# 2.2.2.  Requirement
#
# Any complete sentence containing at least one RFC 2119 keyword MUST
# be treated as a requirement.  A requirement MAY contain multiple RFC
# 2119 keywords.  A requirement MUST be terminated by one of the
# following:
# 
# *  period (.)
# 
# *  exclamation point (!)
# 
# *  list
# 
# *  table
# 
# In the case of requirement terminated by a list, the text proceeding
# the list MUST be concatenated with each element of the list to form a
# requirement.  Taking the above list as an example, Duvet is required
# to be able to recognize 4 different ways to group text into
# requirements.  List elements MAY have RFC 2119 keywords, this is the
# same as regular sentences with multiple keywords.  Sublists MUST be
# treated as if the parent item were terminated by the sublist.  List
# elements MAY contain a period (.) or exclamation point (!) and this
# punctuation MUST NOT terminate the requirement by excluding the
# following elements from the list of requirements.
# 
# In the case of requirement terminated by a table, the text proceeding
# the table SHOULD be concatenated with each row of the table to form a
# requirement.  Table cells MAY have RFC 2119 keywords, this is the
# same as regular sentences with multiple keywords.  Table cells MAY
# contain a period (.) or exclamation point (!) and this punctuation
# MUST NOT terminate the requirement by excluding the following rows
# from the table of requirements.

[[spec]]
level = "MUST"
quote = '''
Any complete sentence containing at least one RFC 2119 keyword MUST
be treated as a requirement.
'''

[[spec]]
level = "MAY"
quote = '''
A requirement MAY contain multiple RFC
2119 keywords.
'''

[[spec]]
level = "MUST"
quote = '''
A requirement MUST be terminated by one of the
following:
'''

[[spec]]
level = "MUST"
quote = '''
In the case of requirement terminated by a list, the text proceeding
the list MUST be concatenated with each element of the list to form a
requirement.
'''

[[spec]]
level = "MAY"
quote = '''
List elements MAY have RFC 2119 keywords, this is the
same as regular sentences with multiple keywords.
'''

[[spec]]
level = "MUST"
quote = '''
Sublists MUST be
treated as if the parent item were terminated by the sublist.
'''

[[spec]]
level = "MUST"
quote = '''
List
elements MAY contain a period (.) or exclamation point (!) and this
punctuation MUST NOT terminate the requirement by excluding the
following elements from the list of requirements.
'''

[[spec]]
level = "SHOULD"
quote = '''
In the case of requirement terminated by a table, the text proceeding
the table SHOULD be concatenated with each row of the table to form a
requirement.
'''

[[spec]]
level = "MAY"
quote = '''
Table cells MAY have RFC 2119 keywords, this is the
same as regular sentences with multiple keywords.
'''

[[spec]]
level = "MUST"
quote = '''
Table cells MAY
contain a period (.) or exclamation point (!) and this punctuation
MUST NOT terminate the requirement by excluding the following rows
from the table of requirements.
'''

