target = "compliance/duvet-specification.txt#2.3.4"

# 2.3.4.  Meta: Reason
#
# A third meta line MAY exist: Reason.  It MUST start with "reason=".
# The rest of this line and the following meta lines MUST be parsed as
# the annotation's reason until there are no more meta lines.

[[spec]]
level = "MUST"
quote = '''
It MUST start with "reason=".
'''

[[spec]]
level = "MAY"
quote = '''
A third meta line MAY exist: Reason.
'''

[[spec]]
level = "MUST"
quote = '''
The rest of this line and the following meta lines MUST be parsed as
the annotation's reason until there are no more meta lines.
'''

