target = "compliance/duvet-specification.txt#2.5.4"

# 2.5.4.  Unexcused
#
# A specification requirement MUST be labeled "Unexcused" and MUST only
# be labeled "Unexcused" if there exists a matching annotation of type
# "exception" and the annotation does NOT have a "reason".

[[spec]]
level = "MUST"
quote = '''
A specification requirement MUST be labeled "Unexcused" and MUST only
be labeled "Unexcused" if there exists a matching annotation of type
"exception" and the annotation does NOT have a "reason".
'''

[[spec]]
level = "MUST"
quote = '''
A specification requirement MUST be labeled "Unexcused" and MUST only
be labeled "Unexcused" if there exists a matching annotation of type
"exception" and the annotation does NOT have a "reason".
'''

