target = "compliance/duvet-specification.txt#2.5.2"

# 2.5.2.  Attested
#
# A specification requirement MUST be labeled "Attested" if there
# exists at least one matching annotation of type
# 
# *  test
# 
# *  untestable
# 
# *  implication

[[spec]]
level = "MUST"
quote = '''
A specification requirement MUST be labeled "Attested" if there
exists at least one matching annotation of type
'''

