source = { local = true }
cmd = ["duvet report"]

[[file]]
path = ".duvet/config.toml"
contents = """
'$schema' = "https://awslabs.github.io/duvet/config/v0.4.0.json"

[[source]]
pattern = "src/my-code.rs"

[[specification]]
source = "my-spec.md"
"""

[[file]]
path = "src/my-code.rs"
contents = """
//= my-spec.md#testing
//# This quote MUST work
//# * with
//# * bullets
"""

[[file]]
path = "my-spec.md"
contents = """
# My spec

here is a spec

## Testing

This quote MUST work
* with
* bullets
"""
