source = { local = true }
cmd = ["duvet report --require-tests"]

[[file]]
path = ".duvet/config.toml"
contents = """
'$schema' = "https://awslabs.github.io/duvet/config/v0.4.0.json"

[[source]]
pattern = "src/my-code.rs"

[[specification]]
source = "my-spec.md"
"""

[[file]]
path = "src/my-code.rs"
contents = """
//= my-spec.md#input-validation
//# The system MUST validate all input parameters before processing.
fn validate_input() {
    // This function has citation but no test - should FAIL with --require-tests
}
"""

[[file]]
path = "my-spec.md"
contents = """
# Input Validation

The system MUST validate all input parameters before processing.
"""
