source = { local = true }
cmd = ["duvet report"]

[[file]]
path = ".duvet/config.toml"
contents = """
'$schema' = "https://awslabs.github.io/duvet/config/v0.4.0.json"

[[source]]
pattern = "src/my-code.rs"

[[specification]]
source = "my-spec.md"
"""

[[file]]
path = "src/my-code.rs"
contents = ""

[[file]]
path = "my-spec.md"
contents = """
# Section

here is a spec
"""
