target = "compliance/spec/spec.txt#2.2.1"

# 2.2.1.  Section
#
# The top level header for requirements is a section.  Sections MUST
# NOT be nested.  A requirements section MUST be the top level
# containing header.  A header MUST NOT itself be a requirement.  A
# section MUST be indexable.  This means that Duvet needs to be able to
# locate it uniquely within a specification.  A good example of a
# section is a header in an HTML or markdown document.

[[spec]]
level = "MUST"
quote = '''
Sections MUST
NOT be nested.
'''

[[spec]]
level = "MUST"
quote = '''
A requirements section MUST be the top level
containing header.
'''

[[spec]]
level = "MUST"
quote = '''
A header MUST NOT itself be a requirement.
'''

[[spec]]
level = "MUST"
quote = '''
A
section MUST be indexable.
'''

