target = "../compliance/Users/yuancc/workspaces/duvet-python/spec/spec.txt#2.2.4.1"

# 2.2.4.1.  Toml
#
# Duvet SHOULD be able to parse requirements formatted as Toml files.
# 
# Duvet SHOULD be able to record parsed requirements into Toml Files.
# 
# These Toml features supports users of Duvet who do not author the
# specifications they are implementing.  As such, they need to
# customize the extracted requirements, modifying the content of
# requirements or adding/removing requirements.

[[spec]]
level = "SHOULD"
quote = '''
Duvet SHOULD be able to parse requirements formatted as Toml files.
'''

[[spec]]
level = "SHOULD"
quote = '''
Duvet SHOULD be able to record parsed requirements into Toml Files.
'''

