target = "compliance/spec/spec.txt#2.4.2"

# 2.4.2.  Matching specification
#
# For an annotation to match a specification the annotation's content
# MUST exist in the specification's section identified by the
# annotation's meta location URL.  The match between the annotation
# content and the specification text MUST be case sensitive but MUST
# NOT be white space sensitive and MUST uniquely identify text in the
# specification.  For simple text in a paragraph this means just
# identifying that the annotation's content is a substring of the text
# in the specification's section.  Elements of a list MUST MUST NOT be
# matched by their order within the list.  This means that an
# annotation may contain a list that is a subset of the elements in the
# specification.  Rows of a table MUST MUST NOT be matched by their
# order within the table.  This means that an annotation may contain a
# table that is a subset of the rows in the specification.

[[spec]]
level = "MUST"
quote = '''
For an annotation to match a specification the annotation's content
MUST exist in the specification's section identified by the
annotation's meta location URL.
'''

[[spec]]
level = "MUST"
quote = '''
The match between the annotation
content and the specification text MUST be case sensitive but MUST
NOT be white space sensitive and MUST uniquely identify text in the
specification.
'''

[[spec]]
level = "MUST"
quote = '''
The match between the annotation
content and the specification text MUST be case sensitive but MUST
NOT be white space sensitive and MUST uniquely identify text in the
specification.
'''

[[spec]]
level = "MUST"
quote = '''
The match between the annotation
content and the specification text MUST be case sensitive but MUST
NOT be white space sensitive and MUST uniquely identify text in the
specification.
'''

[[spec]]
level = "MUST"
quote = '''
Elements of a list MUST MUST NOT be
matched by their order within the list.
'''

[[spec]]
level = "MUST"
quote = '''
Elements of a list MUST MUST NOT be
matched by their order within the list.
'''

[[spec]]
level = "MUST"
quote = '''
Rows of a table MUST MUST NOT be matched by their
order within the table.
'''

[[spec]]
level = "MUST"
quote = '''
Rows of a table MUST MUST NOT be matched by their
order within the table.
'''

