name: Continuous Integration tests

on:
  pull_request:
    branches: [dev-python]
  push:
    branches: [dev-python]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        category:
          - coverage
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r dev_requirements/ci-requirements.txt
      - name: run test
        env:
          TOXENV: ${{ matrix.category }}
        run: tox -- -vv
